### ISSUE TITLE
project template

### ISSUE THREAD

**Issue by patpbe** [RSRBX07/exo-pierre#9]
comment configurer un modèle de projet Rails contenant certains gems pré-installés (ex: bootstrap)
de telle façon que "rails g init" appelle ce modèle.

**Comment by pimpin** [comment]
Attention, je suppose que c'est un lapsus mais que tu ne parles pas de `rails g init` mais bien de `rails new`.

Il est possible de le faire avec l'option -m en lui passant un fichier ruby template d'application.

`rails new my_templatized_app -m ./my_template.rb`

Plus d'info sur l'usage de cette option et le formatage possible des fichiers de template sur [le guide rails](http://edgeguides.rubyonrails.org/rails_application_templates.html).
Je n'ai jamais eu l'occasion de l'utiliser et je ne crois pas que ce soit très couramment utilise.

@patpbe si la réponse te convient, tu peux fermer l'issue.

**Comment by pimpin** [comment]
J'ajoute pour memoire et suite au petit echange de ce soir 
Il m'arrive d'utiliser nouvelles applications rails de temps en temps, mais ce ne sont jamais des application que je crée from scratch.
Ce sont des projets que je clone et dont j'applique les consignes de setup inscrites dans le README.
Ces consignes ressemblent en souvent à ce qui suit.

```bash
git clone projet_x
cd projet_x
bundle install
vim config/database.yml # edit db config
rake db:create
rake db:migrate
rake db:migrate
rails s
```

... voire meme qui de plus en plus ressemble a une simple installation de container docker.
